### ISSUE TITLE
Does it support 32bit platform?

### ISSUE THREAD

**Issue by Nanyan** [phoreproject/bls#17]
Hi there. This project seems to be not supporting 32bit platforms, and I found that some `uint64` numbers are converted to `unit` before doing some calculates in `stub_fallback.go`, such as in the func `AddWithCarry`.

Is there any special considerations here?

Thanks.

**Comment by meyer9** [comment]
I think it can, but we'd have to switch it from `bits.Add` to `bits.Add64`

**Comment by Nanyan** [comment]
I've been making some test on it, it seems that by switching `bits.Add` to `bits.Add64`..., then it will working well both on 64bit and 32bit platforms.

So will you considering to update the code so that it can supports both 64bit os and 32bit os?
