### ISSUE TITLE
Missing domain parameter

### ISSUE THREAD

**Issue by prestonvanloon** [phoreproject/bls#6]
We're blocked on updating the recent changes (https://github.com/prysmaticlabs/prysm/issues/2724) due to an incompatible API change. 

Many of the BLS methods required by ethereum specify using a particular domain for certain data. https://github.com/ethereum/eth2.0-specs/blob/dev/specs/bls_signature.md#hash_to_g2

The API previously supported this until changes in e8b4690ab0071f642301bfd78da5d74c1730c2c1 removed the `domain` parameter.

**Comment by meyer9** [comment]
Fixed in 11029fcb3eb7540e06cce27de39bf876c53446ad

I did not add the uncompressed version because it uses a different format for Jacobian points.
